name: Code Base Chores
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install yarn...
      run: npm install -g yarn
    - name: Installing dependencies...
      run: yarn install
    - name: Running lint...
      run: yarn lint
  tests-and-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install yarn...
      run: npm install yarn
    - name: Installing dependencies...
      run: yarn install
    - name: Testing app...
      run: yarn test --coverage --passWithNoTests
    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info

